version: '3.10'
services:
  telegram_bot_01:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - "/storages:/storages"
    environment:
      DATABASE_URI: ${DATABASE_URI}
    depends_on:
      - db
      - migrations
    restart: always

  db:
    image: postgres:14.3
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command:
      - "postgres"
      - "-c"
      - "port=5433"
    restart: always

  migrations:
    build:
      context: .
    command: bash -c 'while !</dev/tcp/db/5433; do sleep 1; done; alembic upgrade head; ./db_restore.sh'
    restart: "no"
    environment:
      env_file: .env
    depends_on:
      - db
