"""initial migration

Revision ID: 8eed101115a5
Revises: 
Create Date: 2024-03-17 21:58:17.672268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eed101115a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anekdot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=1), nullable=True),
    sa.Column('consecutive', sa.Integer(), nullable=False),
    sa.Column('an_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'date', 'consecutive', name='i_date')
    )
    op.create_table('anekdot_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=1), nullable=True),
    sa.Column('passed', sa.Integer(), nullable=True),
    sa.Column('an_ids', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user', 'category', 'date', name='user_date')
    )
    op.create_index('i_user', 'anekdot_user', ['user'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('file', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_created_at'), 'photos', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_created_at'), table_name='photos')
    op.drop_table('photos')
    op.drop_index('i_user', table_name='anekdot_user')
    op.drop_table('anekdot_user')
    op.drop_table('anekdot')
    # ### end Alembic commands ###
